---
title: "conclusion"
author: "Manunpat"
date: "2022-12-11"
output: html_document
---

# Conclusion      

From the sentiment analysis, we could clearly see that TED talks always posts positive speaks, which can inspire audiences to face challenges and consider the issues from a positive side. On the other hand, we can observe that this situation does not distinguish between the categories of videos, so to some extent there is the lack of diversity in term of the videos' sentiment.    

# Further study and Limitation
One of the limitation is from the data. As the process of obtaining transcript is clicking in each videos to scrape from website, it is hard to have a huge amount of data due to R or our laptop capacity and time limitation. Furthermore, as mentioned in the data preparation part, the structure of the TED website is not perfect for scraping text. Thus, it also brought us difficulties in terms of data richness and diversity. Besides, the distribution of additional features on the TED website is relatively fragmented, such as information about the speakers, comments from viewers, etc. In this case, there are less additional features which are valuable to be used in our analysis.       

Since in our analysis, we could get a not-bad prediction in terms of the categories, as an external analyst, we can broaden our research in response to available information. For example, we can also analyze trends in TED talk releases and predict their release schedule, which can help investors understand what kind of talks TED wants or is capable of organizing in the next year or six months and what messages it will deliver to its audience. Also, since many speakers do not have only one talk in the TED talk module. We can also analyze the variations in the wording of their speeches under the prerequisite of the same speakers or the same topics. Now, TED talks has near to 400 options for choosing videos' categories. From our perspective, it is not perfect for users selecting their favorite topic. Therefore, TED can improve the classification of videos by analyzing what categories viewers' comments on the videos are more inclined to.     
